// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlwuvmoaZNbHADyO7INVW8FoG7YW2RoY',
    appId: '1:128602192923:web:0d756019d8a9121fd3ccbe',
    messagingSenderId: '128602192923',
    projectId: 'tres3-5fdba',
    authDomain: 'tres3-5fdba.firebaseapp.com',
    storageBucket: 'tres3-5fdba.firebasestorage.app',
    measurementId: 'G-LL6DSZ6BEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVnKXyCWwDDvhm_p1xbxIxqD7SKBQXcM',
    appId: '1:128602192923:android:54108a495b0df6f8d3ccbe',
    messagingSenderId: '128602192923',
    projectId: 'tres3-5fdba',
    storageBucket: 'tres3-5fdba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1HwnRdlQtVbjdd6e6fsle1rp4b9LA3Qs',
    appId: '1:128602192923:ios:0f9ab629dbeb9f64d3ccbe',
    messagingSenderId: '128602192923',
    projectId: 'tres3-5fdba',
    storageBucket: 'tres3-5fdba.firebasestorage.app',
    iosBundleId: 'com.threeveesocial.tresvideo',
  );
}
